server:
  port: 5508
  servlet:
    context-path: /api

logging:
  level:
    com.xhpolaris:
      repository: info
    org.springframework.web.filter:
      CommonsRequestLoggingFilter: debug
  file:
    path: logs
  logback:
    rollingpolicy:
      max-history: 30

spring:
  application:
    name: meowchat-mall
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  data:
    redis:
      repositories:
        enabled: false
      host: ${redis.host:localhost}
      port: ${redis.port:6379}
      password: ${redis.password}
      database: 0
  cache:
    type: redis
  profiles:
    active: default
  mvc:
    path-match:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

grpc:
  client:
    meowchat-content:
      address: "static://meowchat-content.xh-polaris:8080"
      enable-keep-alive: true
      negotiationType: PLAINTEXT
